use swiggy;
SELECT * from restaurants;

-- 1. list the top 5 cuisines as per the revenue generated by the top 5 restaurants of every cuisine
select  cuisine ,sum(rating_count*cost) as 'revenue'from 
(Select *,cost*rating_count,
ROW_NUMBER() over (PARTITION BY cuisine order by cost*rating_count desc ) as 'rank' from restaurants) t 
where t.rank <6
group by cuisine 
order by revenue desc;

-- 2. what % of total revenue is generated by top 1% restaurants 
 select sum(cost*rating_count) as 'revenue' from 
    (select *, cost*rating_count, row_number() over(order by cost*rating_count desc )as 'rank'
    from restaurants)t
    where t.rank <= 614;
  
-- 3. check the same for top 20 % restaurants 
 select sum(cost*rating_count) as 'revenue' from 
    (select *, cost*rating_count, row_number() over(order by cost*rating_count desc )as 'rank'
    from restaurants)t
    where t.rank <= 12280;
  
-- 4. what % of revenue is generated by top 20 % of restaurants with respect to total revenuue 
with
    q1 as ( select sum(cost*rating_count) as 'top_revenue' from 
    (select *, cost*rating_count, row_number() over(order by cost*rating_count desc )as 'rank'
    from restaurants)t
    where t.rank <= 12280),
    q2 as (select sum(cost*rating_count) as 'total_revenue' from restaurants)
    
select (top_revenue / total_revenue)*100 as 'revenue %' from q1,q2;